# .github/workflows/self-hosted-runner.yml
name: CI on Self-Hosted Runner

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: self-hosted  # Specify that this job should run on a self-hosted runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run a simple shell command (example: print environment info)
      - name: sast
        run: |
          echo "Running sast self-hosted runner"
          mkdir /tmp/"$GITHUB_SHA"
          /opt/scancentral/bin/scancentral -url ${{ vars.PROD_SC_CONTROLLER_URL }} start -upload -versionid ${{ vars.VERSION_ID }} -uptoken ${{ vars.SSC_UPLOAD_TOKEN }} -fprssc "$GITHUB_SHA.fpr"  | grep "Submitted job and received" | cut -d ":" -f 2 > /tmp/"$GITHUB_SHA"/job-token.txt
          cat /tmp/"$GITHUB_SHA"/job-token.txt
          /opt/scancentral/bin/check-scan.sh $PROD_SC_CONTROLLER_URL
          rm -rf /tmp/"$GITHUB_SHA"/job-token.txt
          

          
          
